export const INITIAL_ORDERS = [
  // Flow 1: Seller -> SHG (Pickup Pending)
  {
    id: 'ORD-001',
    productName: 'Handmade Silk Saree',
    flowType: 'SELLER_TO_TRANSPORTER',
    fromType: 'SELLER',
    toType: 'TRANSPORTER',
    currentHolder: 'SELLER',
    from: 'Priya SHG (Seller)',
    to: 'Rajesh (Transporter)',
    address: 'B-402, Green Valley, Pune',
    phone: '9876543210',
    status: 'assigned',
    totalQty: 5,
    deliveredQty: 0,
    remainingQty: 5,
    date: new Date().toISOString(),
    priority: 'high',
  },
  // Flow 2: Transporter -> SHG (Pickup Pending)
  {
    id: 'ORD-002',
    productName: 'Organic Honey (500g)',
    flowType: 'TRANSPORTER_TO_BUYER',
    fromType: 'TRANSPORTER',
    toType: 'BUYER',
    currentHolder: 'TRANSPORTER',
    from: 'Suresh (Transporter)',
    to: 'Anita (Buyer)',
    address: 'Flat 101, Sunshine Apartments, Mumbai',
    phone: '9123456789',
    status: 'assigned',
    totalQty: 10,
    deliveredQty: 0,
    remainingQty: 10,
    date: new Date(Date.now() - 3600000).toISOString(),
    priority: 'medium',
  },
  // SHG holding product (Drop Pending)
  {
    id: 'ORD-003',
    productName: 'Jute Bags (Set of 10)',
    flowType: 'SELLER_TO_TRANSPORTER',
    fromType: 'SHG',
    toType: 'TRANSPORTER',
    currentHolder: 'SHG',
    from: 'My SHG',
    to: 'Vikram (Transporter)',
    address: 'City Hub, Navi Mumbai',
    phone: '9822113344',
    status: 'at_home',
    totalQty: 12,
    deliveredQty: 0,
    remainingQty: 12,
    date: new Date(Date.now() - 7200000).toISOString(),
    priority: 'low',
  },
  // Exchange Scenario: Vikram Transporter
  // 1. Pickup from Vikram
  {
    id: 'EXCH-P1',
    productName: 'Spices Gift Box',
    flowType: 'TRANSPORTER_TO_BUYER',
    fromType: 'TRANSPORTER',
    toType: 'SHG',
    currentHolder: 'TRANSPORTER',
    from: 'Vikram (Transporter)',
    to: 'My SHG',
    address: 'Vashi Market, Navi Mumbai',
    phone: '9822113344',
    status: 'assigned',
    totalQty: 20,
    deliveredQty: 0,
    remainingQty: 20,
    date: new Date().toISOString(),
    priority: 'high',
  },
  // 2. Drop to Vikram
  {
    id: 'EXCH-D1',
    productName: 'Cotton Bedspreads',
    flowType: 'SELLER_TO_TRANSPORTER',
    fromType: 'SHG',
    toType: 'TRANSPORTER',
    currentHolder: 'SHG',
    from: 'My SHG',
    to: 'Vikram (Transporter)',
    address: 'Vashi Market, Navi Mumbai',
    phone: '9822113344',
    status: 'at_home',
    totalQty: 15,
    deliveredQty: 0,
    remainingQty: 15,
    date: new Date().toISOString(),
    priority: 'medium',
  },
  // An older order for history testing
  {
    id: 'ORD-004',
    productName: 'Bamboo Handicrafts',
    flowType: 'SELLER_TO_TRANSPORTER',
    fromType: 'SELLER',
    toType: 'TRANSPORTER',
    currentHolder: 'TRANSPORTER',
    from: 'Rural Artisans',
    to: 'State Hub',
    address: 'Collector Office Road, Satara',
    phone: '9000011111',
    status: 'delivered',
    totalQty: 50,
    deliveredQty: 50,
    remainingQty: 0,
    date: new Date(Date.now() - 172800000).toISOString(), // 2 days ago
    priority: 'low',
  }
];
